
@hostname = localhost:7000

### Get all items:

GET http://{{hostname}}/api/menu/items
Content-Type: application/json

### Get an item:
GET http://{{hostname}}/api/menu/items/2

### Add an item:
POST http://{{hostname}}/api/menu/items
Content-Type: application/json

{
    "name": "Salad",
    "price": 499,
    "description": "Fresh",
    "image": "https://images.ctfassets.net/23aumh6u8s0i/5pnNAeu0kev0P5Neh9W0jj/5b62440be149d0c1a9cb84a255662205/whatabyte_salad-sm.png"
}

###  Update an item:
PUT http://{{hostname}}/api/menu/items/2
Content-Type: application/json

{
  "name": "Spicy Pizza",
  "price": 599,
  "description": "Blazing Good",
  "image": "https://images.ctfassets.net/23aumh6u8s0i/2x1D2KeepKoZlsUq0SEsOu/bee61947ed648848e99c71ce22563849/whatabyte_pizza-sm.png"
}


###  Delete an item:
DELETE  http://{{hostname}}/api/menu/items/1665932399693
Content-Type: application/json
